image: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: \PSO2ModManager\bin\x86\Release\**\*
  name: PSO2ModManager
  type: zip
- path: \PSO2ModManager\bin\x86\Release\**\*
  name: PSO2ModManager
  type: zip