//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSO2ModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSO2ModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check for Updates.
        /// </summary>
        internal static string CommandButton_CheckUpdate {
            get {
                return ResourceManager.GetString("CommandButton.CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open a mod file.
        /// </summary>
        internal static string CommandButton_OpenMod {
            get {
                return ResourceManager.GetString("CommandButton.OpenMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string CommandButton_Setting {
            get {
                return ResourceManager.GetString("CommandButton.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now checking update....
        /// </summary>
        internal static string Dialog_CheckingUpdate {
            get {
                return ResourceManager.GetString("Dialog.CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now downloading..
        /// </summary>
        internal static string Dialog_Downloading {
            get {
                return ResourceManager.GetString("Dialog.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait....
        /// </summary>
        internal static string Dialog_WaitTitle {
            get {
                return ResourceManager.GetString("Dialog.WaitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: Please remember that this software could damage your PSO2 installation. Also please note that Sega does not endorse nor condone modding in any way or form, thus this can get you banned. We&apos;re not responsible/liable if your account is banned. Play at your own risk, thanks..
        /// </summary>
        internal static string Dialog_Welcome {
            get {
                return ResourceManager.GetString("Dialog.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Important.
        /// </summary>
        internal static string Dialog_WelcomeTitle {
            get {
                return ResourceManager.GetString("Dialog.WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when checking for updates..
        /// </summary>
        internal static string Error_CheckingUpdate {
            get {
                return ResourceManager.GetString("Error.CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when downlading mod(s)..
        /// </summary>
        internal static string Error_DownloadingTitle {
            get {
                return ResourceManager.GetString("Error.DownloadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currently downloading another mod(s).Please wait until it&apos;s installed..
        /// </summary>
        internal static string Error_MultipleDownloadProcess {
            get {
                return ResourceManager.GetString("Error.MultipleDownloadProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mod not compatible with mod tool..
        /// </summary>
        internal static string Error_NotCompatible {
            get {
                return ResourceManager.GetString("Error.NotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PSO2 Mod files.
        /// </summary>
        internal static string FileDialog_Filter {
            get {
                return ResourceManager.GetString("FileDialog.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the pso2 data/win32 directory.
        /// </summary>
        internal static string FolderBrowser_SelectPso2Dir {
            get {
                return ResourceManager.GetString("FolderBrowser.SelectPso2Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Broken).
        /// </summary>
        internal static string Mod_Broken {
            get {
                return ResourceManager.GetString("Mod.Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Local).
        /// </summary>
        internal static string Mod_Local {
            get {
                return ResourceManager.GetString("Mod.Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Update Available).
        /// </summary>
        internal static string Mod_Update {
            get {
                return ResourceManager.GetString("Mod.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available mods.
        /// </summary>
        internal static string ModTab_AvailableMods {
            get {
                return ResourceManager.GetString("ModTab.AvailableMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Mod.
        /// </summary>
        internal static string ModTab_Button_Delete {
            get {
                return ResourceManager.GetString("ModTab.Button.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Install.
        /// </summary>
        internal static string ModTab_Button_Install {
            get {
                return ResourceManager.GetString("ModTab.Button.Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uninstall.
        /// </summary>
        internal static string ModTab_Button_Uninstall {
            get {
                return ResourceManager.GetString("ModTab.Button.Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string ModTab_Button_Update {
            get {
                return ResourceManager.GetString("ModTab.Button.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View on PSO2 Mod DB.
        /// </summary>
        internal static string ModTab_Button_VisitSite {
            get {
                return ResourceManager.GetString("ModTab.Button.VisitSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installed mods.
        /// </summary>
        internal static string ModTab_InstalledMods {
            get {
                return ResourceManager.GetString("ModTab.InstalledMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string Settings_Color {
            get {
                return ResourceManager.GetString("Settings.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search/Install Mods.
        /// </summary>
        internal static string Tab_BrowseMods {
            get {
                return ResourceManager.GetString("Tab.BrowseMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installed Mods.
        /// </summary>
        internal static string Tab_LocalMods {
            get {
                return ResourceManager.GetString("Tab.LocalMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to zoom image..
        /// </summary>
        internal static string Tooltip_Thumbnail {
            get {
                return ResourceManager.GetString("Tooltip.Thumbnail", resourceCulture);
            }
        }
    }
}
